apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace: nobel
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: nobel
spec:
  type: LoadBalancer
  selector:
    app: search
  ports:
    - port: 80
      targetPort: 80
